/***************************************************************** 
 * this script is generated by fgta5 generator version 1.2
 * DO NOT modify this script! All modification will lost on regeneration
 **************************************************************** */

import pgp from 'pg-promise';

import db from '@agung_dhewe/webapps/src/db.js'
import Api from '@agung_dhewe/webapps/src/api.js'
import sqlUtil from '@agung_dhewe/pgsqlc'
import context from '@agung_dhewe/webapps/src/context.js'  
import logger from '@agung_dhewe/webapps/src/logger.js'
import { createSequencerLine } from '@agung_dhewe/webapps/src/sequencerline.js' 

import * as Extender from './extenders/adendum.apiext.js'

const moduleName = 'adendum'
const headerSectionName = 'header'
const headerTableName = 'public.adendum' 
const brandTableName = 'public.adendumbrand'  
const marginTableName = 'public.adendummargin'  	

// api: account
export default class extends Api {
	constructor(req, res, next) {
		super(req, res, next);
		Api.cekLogin(req)
	}


	// dipanggil dengan model snake syntax
	// contoh: header-list
	//         header-open-data
	async init(body) { return await adendum_init(this, body) }

	// extender call
	async execute(body) { return await adendum_execute(this, body) }

	// header
	async headerList(body) { return await adendum_headerList(this, body) }
	async headerOpen(body) { return await adendum_headerOpen(this, body) }
	async headerUpdate(body) { return await adendum_headerUpdate(this, body)}
	async headerCreate(body) { return await adendum_headerCreate(this, body)}
	async headerDelete(body) { return await adendum_headerDelete(this, body) }

	
	// brand	
	async brandList(body) { return await adendum_brandList(this, body) }
	async brandOpen(body) { return await adendum_brandOpen(this, body) }
	async brandUpdate(body) { return await adendum_brandUpdate(this, body)}
	async brandCreate(body) { return await adendum_brandCreate(this, body) }
	async brandDelete(body) { return await adendum_brandDelete(this, body) }
	async brandDeleteRows(body) { return await adendum_brandDeleteRows(this, body) }
	
	// margin	
	async marginList(body) { return await adendum_marginList(this, body) }
	async marginOpen(body) { return await adendum_marginOpen(this, body) }
	async marginUpdate(body) { return await adendum_marginUpdate(this, body)}
	async marginCreate(body) { return await adendum_marginCreate(this, body) }
	async marginDelete(body) { return await adendum_marginDelete(this, body) }
	async marginDeleteRows(body) { return await adendum_marginDeleteRows(this, body) }
			
}	

// init module
async function adendum_init(self, body) {
	const req = self.req

	// set sid untuk session ini, diperlukan ini agar session aktif
	req.session.sid = req.sessionID

	try {
		// ambil data app dari database
		const sql = 'select apps_id, apps_url from core."apps"'
		const result = await db.any(sql)

		const appsUrls = {}
		for (let row of result) {
			appsUrls[row.apps_id] = {
				url: row.apps_url
			}
		}

		const initialData = {
			userId: req.session.user.userId,
			userName: req.session.user.userName,
			userFullname: req.session.userFullname,
			sid: req.session.sid ,
			notifierId: Api.generateNotifierId(moduleName, req.sessionID),
			notifierSocket: req.app.locals.appConfig.notifierSocket,
			appName: req.app.locals.appConfig.appName,
			appsUrls: appsUrls,
			setting: {}
		}
		
		if (typeof Extender.adendum_init === 'function') {
			// export async function adendum_init(self, initialData) {}
			await Extender.adendum_init(self, initialData)
		}

		return initialData
		
	} catch (err) {
		throw err
	}
}


// execute extender function
async function adendum_execute(self, body) {
	const { fnName } = body

	if (fnName==null || fnName=='') {
		throw new Error('fnName belum didefinisikan di api call') 
	}

	if (typeof Extender[fnName] === 'function') {
		// export async function [fnName](self, db, body, adendum_log) {}
		return await Extender[fnName](self, db, body, adendum_log)
	} else {
		// api function extender tidak ditemukan
		throw new Error(`${fnName} tidak ditmukan di extender`)
	}
}


// data logging
async function adendum_log(self, body, startTime, tablename, id, action, data={}, remark='') {
	const { source } = body
	const req = self.req
	const user_id = req.session.user.userId
	const user_name = req.session.user.userFullname
	const ipaddress = req.ip
	const metadata = JSON.stringify({...{source:source}, ...data})
	const endTime = process.hrtime.bigint();
	const executionTimeMs = Number((endTime - startTime) / 1_000_000n); // hasil dalam ms tanpa desimal
	
	const logdata = {id, user_id, user_name, moduleName, action, tablename, executionTimeMs, remark, metadata, ipaddress}
	const ret = await logger.log(logdata)
	return ret
}





async function adendum_headerList(self, body) {
	const tablename = headerTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		searchtext: `adendum_id=try_cast_bigint(\${searchtext}, 0)`,
	};

	try {
	
		// jika tidak ada default searchtext
		if (searchMap.searchtext===undefined) {
			throw new Error(`'searchtext' belum didefinisikan di searchMap`)	
		}
		

		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.headerListCriteria === 'function') {
			// export async function headerListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.headerListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort,
			limit:max_rows+1, 
			offset, 
			queryParams
		})

		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			// lookup: agreement_desc dari field agreement_desc pada table public.agreement dimana (public.agreement.agreement_id = public.adendum.agreement_id)
			{
				const { agreement_desc } = await sqlUtil.lookupdb(db, 'public.agreement', 'agreement_id', row.agreement_id)
				row.agreement_desc = agreement_desc
			}
			// lookup: adendumtype_name dari field adendumtype_name pada table public.adendumtype dimana (public.adendumtype.adendumtype_id = public.adendum.adendumtype_id)
			{
				const { adendumtype_name } = await sqlUtil.lookupdb(db, 'public.adendumtype', 'adendumtype_id', row.adendumtype_id)
				row.adendumtype_name = adendumtype_name
			}
			
			// pasang extender di sini
			if (typeof Extender.headerListRow === 'function') {
				// export async function headerListRow(self, row, args) {}
				await Extender.headerListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}

		return {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

	} catch (err) {
		throw err
	}
}

async function adendum_headerOpen(self, body) {
	const tablename = headerTableName

	try {
		const { id } = body 
		const criteria = { adendum_id: id }
		const searchMap = { adendum_id: `adendum_id = \${adendum_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	

		// lookup: agreement_desc dari field agreement_desc pada table public.agreement dimana (public.agreement.agreement_id = public.adendum.agreement_id)
		{
			const { agreement_desc } = await sqlUtil.lookupdb(db, 'public.agreement', 'agreement_id', data.agreement_id)
			data.agreement_desc = agreement_desc
		}
		// lookup: adendumtype_name dari field adendumtype_name pada table public.adendumtype dimana (public.adendumtype.adendumtype_id = public.adendum.adendumtype_id)
		{
			const { adendumtype_name } = await sqlUtil.lookupdb(db, 'public.adendumtype', 'adendumtype_id', data.adendumtype_id)
			data.adendumtype_name = adendumtype_name
		}
		

		// lookup data createby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}
		
		// pasang extender untuk olah data
		// export async function headerOpen(self, db, data) {}
		if (typeof Extender.headerOpen === 'function') {
			// export async function headerOpen(self, db, data) {}
			await Extender.headerOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}


async function adendum_headerCreate(self, body) {
	const { source='adendum', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = headerTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._createby = user_id
		data._createdate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { section: 'header', doc_id:'ADD' }

			
			// buat short sequencer	
			const sequencer = createSequencerLine(tx, {})

			if (typeof Extender.sequencerSetup === 'function') {
				// jika ada keperluan menambahkan code block/cluster di sequencer
				// dapat diimplementasikan di exterder sequencerSetup 
				// export async function sequencerSetup(self, tx, sequencer, data, args) {}
				await Extender.sequencerSetup(self, tx, sequencer, data, args)
			}

			// generate short id sesuai prefix (default: ADD) reset pertahun
			const seqdata = await sequencer.yearlyshort(args.doc_id)
			data.adendum_id = seqdata.id

			// apabila ada keperluan pengelohan data sebelum disimpan, lakukan di extender headerCreating
			if (typeof Extender.headerCreating === 'function') {
				// export async function headerCreating(self, tx, data, seqdata, args) {}
				await Extender.headerCreating(self, tx, data, seqdata, args)
			}

			

			const cmd = sqlUtil.createInsertCommand(tablename, data)
			const ret = await cmd.execute(data)

			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.headerCreated === 'function') {
				// export async function headerCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.headerCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			adendum_log(self, body, startTime, tablename, ret.adendum_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function adendum_headerUpdate(self, body) {
	const { source='adendum', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = headerTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._modifyby = user_id
		data._modifydate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			// apabila ada keperluan pengelohan data sebelum disimpan, lakukan di extender headerCreating
			if (typeof Extender.headerUpdating === 'function') {
				// export async function headerUpdating(self, tx, data) {}
				await Extender.headerUpdating(self, tx, data)
			}

			// eksekusi update
			const cmd = sqlUtil.createUpdateCommand(tablename, data, ['adendum_id'])
			const ret = await cmd.execute(data)

			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.headerUpdated === 'function') {
				// export async function headerUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.headerUpdated(self, tx, ret, data, logMetadata)
			}			

			// record log
			adendum_log(self, body, startTime, tablename, data.adendum_id, 'UPDATE')

			return ret
		})
		

		return result
	} catch (err) {
		throw err
	}
}


async function adendum_headerDelete(self, body) {
	const { source, id } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = headerTableName

	try {

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {adendum_id: id}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender headerDeleting
			if (typeof Extender.headerDeleting === 'function') {
				// export async function headerDeleting(self, tx, dataToRemove) {}
				await Extender.headerDeleting(self, tx, dataToRemove)
			}

			
			// hapus data brand
			{
				const sql = `select * from ${brandTableName} where adendum_id=\${adendum_id}`
				const rows = await tx.any(sql, dataToRemove)
				for (let rowbrand of rows) {
					
					const logMetadata = {}
					
					// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
					if (typeof Extender.brandDeleting === 'function') {
						// export async function brandDeleting(self, tx, rowbrand, logMetadata) {}
						await Extender.brandDeleting(self, tx, rowbrand, logMetadata)
					}

					const param = {adendumbrand_id: rowbrand.adendumbrand_id}
					const cmd = sqlUtil.createDeleteCommand(brandTableName, ['adendumbrand_id'])
					const deletedRow = await cmd.execute(param)

					// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
					if (typeof Extender.brandDeleted === 'function') {
						// export async function brandDeleted(self, tx, deletedRow, logMetadata) {}
						await Extender.brandDeleted(self, tx, deletedRow, logMetadata)
					}					

					adendum_log(self, body, startTime, brandTableName, rowbrand.adendumbrand_id, 'DELETE', {rowdata: deletedRow})
					adendum_log(self, body, startTime, headerTableName, rowbrand.adendum_id, 'DELETE ROW BRAND', {adendumbrand_id: rowbrand.adendumbrand_id, tablename: brandTableName}, `removed: ${rowbrand.adendumbrand_id}`)


				}	
			}

			// hapus data margin
			{
				const sql = `select * from ${marginTableName} where adendum_id=\${adendum_id}`
				const rows = await tx.any(sql, dataToRemove)
				for (let rowmargin of rows) {
					
					const logMetadata = {}
					
					// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
					if (typeof Extender.marginDeleting === 'function') {
						// export async function marginDeleting(self, tx, rowmargin, logMetadata) {}
						await Extender.marginDeleting(self, tx, rowmargin, logMetadata)
					}

					const param = {adendummargin_id: rowmargin.adendummargin_id}
					const cmd = sqlUtil.createDeleteCommand(marginTableName, ['adendummargin_id'])
					const deletedRow = await cmd.execute(param)

					// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
					if (typeof Extender.marginDeleted === 'function') {
						// export async function marginDeleted(self, tx, deletedRow, logMetadata) {}
						await Extender.marginDeleted(self, tx, deletedRow, logMetadata)
					}					

					adendum_log(self, body, startTime, marginTableName, rowmargin.adendummargin_id, 'DELETE', {rowdata: deletedRow})
					adendum_log(self, body, startTime, headerTableName, rowmargin.adendum_id, 'DELETE ROW MARGIN', {adendummargin_id: rowmargin.adendummargin_id, tablename: marginTableName}, `removed: ${rowmargin.adendummargin_id}`)


				}	
			}

			
			

			// hapus data header
			const cmd = sqlUtil.createDeleteCommand(tablename, ['adendum_id'])
			const deletedRow = await cmd.execute(dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender headerDeleted
			if (typeof Extender.headerDeleted === 'function') {
				// export async function headerDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.headerDeleted(self, tx, deletedRow, logMetadata)
			}

			// record log
			adendum_log(self, body, startTime, tablename, id, 'DELETE', logMetadata)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}



// brand	

async function adendum_brandList(self, body) {
	const tablename = brandTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		adendum_id: `adendum_id=try_cast_bigint(\${adendum_id}, 0)`,
	};


	if (Object.keys(sort).length === 0) {
		sort.adendumbrand_id = 'asc'
	}


	try {
	
		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.brandListCriteria === 'function') {
			// export async function brandListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.brandListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort, 
			limit:max_rows+1, 
			offset, 
			queryParams
		})
		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			// lookup: brand_name dari field brand_name pada table public.brand dimana (public.brand.brand_id = public.adendum.brand_id)
			{
				const { brand_name } = await sqlUtil.lookupdb(db, 'public.brand', 'brand_id', row.brand_id)
				row.brand_name = brand_name
			}
			

			// pasang extender di sini
			if (typeof Extender.detilListRow === 'function') {
				// export async function detilListRow(self, row, args) {}
				await Extender.detilListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}


		const listData = {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

		if (typeof Extender.detilList === 'function') {
			// export async function detilList(self, listData, args) {}
			await Extender.detilList(self, listData, args)
		}

		return listData
	} catch (err) {
		throw err
	}
}

async function adendum_brandOpen(self, body) {
	const tablename = brandTableName

	try {
		const { id } = body 
		const criteria = { adendumbrand_id: id }
		const searchMap = { adendumbrand_id: `adendumbrand_id = \${adendumbrand_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	


		// lookup: brand_name dari field brand_name pada table public.brand dimana (public.brand.brand_id = public.adendum.brand_id)
		{
			const { brand_name } = await sqlUtil.lookupdb(db, 'public.brand', 'brand_id', data.brand_id)
			data.brand_name = brand_name
		}
		

		// lookup data createby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}	


		// pasang extender untuk olah data
		// export async function brandOpen(self, db, data) {}
		if (typeof Extender.brandOpen === 'function') {
			// export async function brandOpen(self, db, data) {}
			await Extender.brandOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}

async function adendum_brandCreate(self, body) {
	const { source='adendum', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = brandTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._createby = user_id
		data._createdate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { 
				section: 'brand', 
				prefix: 'ADD'	
			}

			const sequencer = createSequencerLine(tx, {})


			if (typeof Extender.sequencerSetup === 'function') {
				// jika ada keperluan menambahkan code block/cluster di sequencer
				// dapat diimplementasikan di exterder sequencerSetup 
				// export async function sequencerSetup(self, tx, sequencer, data, args) {}
				await Extender.sequencerSetup(self, tx, sequencer, data, args)
			}


			const seqdata = await sequencer.increment(args.prefix)
			data.adendumbrand_id = seqdata.id

			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.brandCreating === 'function') {
				// export async function brandCreating(self, tx, data, seqdata, args) {}
				await Extender.brandCreating(self, tx, data, seqdata, args)
			}

			const cmd = sqlUtil.createInsertCommand(tablename, data)
			const ret = await cmd.execute(data)
			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.brandCreated === 'function') {
				// export async function brandCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.brandCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			adendum_log(self, body, startTime, tablename, ret.adendumbrand_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function adendum_brandUpdate(self, body) {
	const { source='adendum', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = brandTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._modifyby = user_id
		data._modifydate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.brandUpdating === 'function') {
				// export async function brandUpdating(self, tx, data) {}
				await Extender.brandUpdating(self, tx, data)
			}			
			
			const cmd =  sqlUtil.createUpdateCommand(tablename, data, ['adendumbrand_id'])
			const ret = await cmd.execute(data)
			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.brandUpdated === 'function') {
				// export async function brandUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.brandUpdated(self, tx, ret, data, logMetadata)
			}

			// record log
			adendum_log(self, body, startTime, tablename, data.adendumbrand_id, 'UPDATE', logMetadata)

			return ret
		})
	
		return result
	} catch (err) {
		throw err
	}
}

async function adendum_brandDelete(self, body) {
	const { source, id } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = brandTableName

	try {

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {adendumbrand_id: id}
			const sql = `select * from ${brandTableName} where adendumbrand_id=\${adendumbrand_id}`
			const rowbrand = await tx.oneOrNone(sql, dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
			if (typeof Extender.brandDeleting === 'function') {
				// export async function brandDeleting(self, tx, rowbrand, logMetadata) {}
				await Extender.brandDeleting(self, tx, rowbrand, logMetadata)
			}

			const param = {adendumbrand_id: rowbrand.adendumbrand_id}
			const cmd = sqlUtil.createDeleteCommand(brandTableName, ['adendumbrand_id'])
			const deletedRow = await cmd.execute(param)

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
			if (typeof Extender.brandDeleted === 'function') {
				// export async function brandDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.brandDeleted(self, tx, deletedRow, logMetadata)
			}					

			adendum_log(self, body, startTime, brandTableName, rowbrand.adendumbrand_id, 'DELETE', {rowdata: deletedRow})
			adendum_log(self, body, startTime, headerTableName, rowbrand.adendum_id, 'DELETE ROW BRAND', {adendumbrand_id: rowbrand.adendumbrand_id, tablename: brandTableName}, `removed: ${rowbrand.adendumbrand_id}`)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}

async function adendum_brandDeleteRows(self, body) {
	const { data } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = brandTableName


	try {

		let adendum_id
		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			for (let id of data) {
				const dataToRemove = {adendumbrand_id: id}
				const sql = `select * from ${brandTableName} where adendumbrand_id=\${adendumbrand_id}`
				const rowbrand = await tx.oneOrNone(sql, dataToRemove)
				adendum_id = rowbrand.adendum_id

				const logMetadata = {}

				
				// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
				if (typeof Extender.brandDeleting === 'function') {
					// async function brandDeleting(self, tx, rowbrand, logMetadata) {}
					await Extender.brandDeleting(self, tx, rowbrand, logMetadata)
				}

				const param = {adendumbrand_id: rowbrand.adendumbrand_id}
				const cmd = sqlUtil.createDeleteCommand(brandTableName, ['adendumbrand_id'])
				const deletedRow = await cmd.execute(param)

				// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
				if (typeof Extender.brandDeleted === 'function') {
					// export async function brandDeleted(self, tx, deletedRow, logMetadata) {}
					await Extender.brandDeleted(self, tx, deletedRow, logMetadata)
				}					

				adendum_log(self, body, startTime, brandTableName, rowbrand.adendumbrand_id, 'DELETE', {rowdata: deletedRow})
				adendum_log(self, body, startTime, headerTableName, rowbrand.adendum_id, 'DELETE ROW BRAND', {adendumbrand_id: rowbrand.adendumbrand_id, tablename: brandTableName}, `removed: ${rowbrand.adendumbrand_id}`)
			}
		})
		

		const res = {
			deleted: true,
			adendum_id: adendum_id,
			message: ''
		}

		// apabila ada keperluan update info / pemrosesan data setelah hapus multirow, lakukan di extender
		const fn_name = 'brandRowsDeleted'
		const fn = Extender[fn_name]
		if (typeof fn === 'function') {
			// export async function brandRowsDeleted(self, db, res) {}
			await fn(self, db, res)
		}

		return res
	} catch (err) {
		throw err
	}	
}


// margin	

async function adendum_marginList(self, body) {
	const tablename = marginTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		adendum_id: `adendum_id=try_cast_bigint(\${adendum_id}, 0)`,
	};


	if (Object.keys(sort).length === 0) {
		sort.adendummargin_id = 'asc'
	}


	try {
	
		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.marginListCriteria === 'function') {
			// export async function marginListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.marginListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort, 
			limit:max_rows+1, 
			offset, 
			queryParams
		})
		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			// lookup: marginrange_desc dari field marginrange_desc pada table public.marginrange dimana (public.marginrange.marginrange_id = public.adendum.marginrange_id)
			{
				const { marginrange_desc } = await sqlUtil.lookupdb(db, 'public.marginrange', 'marginrange_id', row.marginrange_id)
				row.marginrange_desc = marginrange_desc
			}
			

			// pasang extender di sini
			if (typeof Extender.detilListRow === 'function') {
				// export async function detilListRow(self, row, args) {}
				await Extender.detilListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}


		const listData = {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

		if (typeof Extender.detilList === 'function') {
			// export async function detilList(self, listData, args) {}
			await Extender.detilList(self, listData, args)
		}

		return listData
	} catch (err) {
		throw err
	}
}

async function adendum_marginOpen(self, body) {
	const tablename = marginTableName

	try {
		const { id } = body 
		const criteria = { adendummargin_id: id }
		const searchMap = { adendummargin_id: `adendummargin_id = \${adendummargin_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	


		// lookup: marginrange_desc dari field marginrange_desc pada table public.marginrange dimana (public.marginrange.marginrange_id = public.adendum.marginrange_id)
		{
			const { marginrange_desc } = await sqlUtil.lookupdb(db, 'public.marginrange', 'marginrange_id', data.marginrange_id)
			data.marginrange_desc = marginrange_desc
		}
		

		// lookup data createby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}	


		// pasang extender untuk olah data
		// export async function marginOpen(self, db, data) {}
		if (typeof Extender.marginOpen === 'function') {
			// export async function marginOpen(self, db, data) {}
			await Extender.marginOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}

async function adendum_marginCreate(self, body) {
	const { source='adendum', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = marginTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._createby = user_id
		data._createdate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { 
				section: 'margin', 
				prefix: 'ADD'	
			}

			const sequencer = createSequencerLine(tx, {})


			if (typeof Extender.sequencerSetup === 'function') {
				// jika ada keperluan menambahkan code block/cluster di sequencer
				// dapat diimplementasikan di exterder sequencerSetup 
				// export async function sequencerSetup(self, tx, sequencer, data, args) {}
				await Extender.sequencerSetup(self, tx, sequencer, data, args)
			}


			const seqdata = await sequencer.increment(args.prefix)
			data.adendummargin_id = seqdata.id

			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.marginCreating === 'function') {
				// export async function marginCreating(self, tx, data, seqdata, args) {}
				await Extender.marginCreating(self, tx, data, seqdata, args)
			}

			const cmd = sqlUtil.createInsertCommand(tablename, data)
			const ret = await cmd.execute(data)
			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.marginCreated === 'function') {
				// export async function marginCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.marginCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			adendum_log(self, body, startTime, tablename, ret.adendummargin_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function adendum_marginUpdate(self, body) {
	const { source='adendum', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = marginTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._modifyby = user_id
		data._modifydate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.marginUpdating === 'function') {
				// export async function marginUpdating(self, tx, data) {}
				await Extender.marginUpdating(self, tx, data)
			}			
			
			const cmd =  sqlUtil.createUpdateCommand(tablename, data, ['adendummargin_id'])
			const ret = await cmd.execute(data)
			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.marginUpdated === 'function') {
				// export async function marginUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.marginUpdated(self, tx, ret, data, logMetadata)
			}

			// record log
			adendum_log(self, body, startTime, tablename, data.adendummargin_id, 'UPDATE', logMetadata)

			return ret
		})
	
		return result
	} catch (err) {
		throw err
	}
}

async function adendum_marginDelete(self, body) {
	const { source, id } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = marginTableName

	try {

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {adendummargin_id: id}
			const sql = `select * from ${marginTableName} where adendummargin_id=\${adendummargin_id}`
			const rowmargin = await tx.oneOrNone(sql, dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
			if (typeof Extender.marginDeleting === 'function') {
				// export async function marginDeleting(self, tx, rowmargin, logMetadata) {}
				await Extender.marginDeleting(self, tx, rowmargin, logMetadata)
			}

			const param = {adendummargin_id: rowmargin.adendummargin_id}
			const cmd = sqlUtil.createDeleteCommand(marginTableName, ['adendummargin_id'])
			const deletedRow = await cmd.execute(param)

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
			if (typeof Extender.marginDeleted === 'function') {
				// export async function marginDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.marginDeleted(self, tx, deletedRow, logMetadata)
			}					

			adendum_log(self, body, startTime, marginTableName, rowmargin.adendummargin_id, 'DELETE', {rowdata: deletedRow})
			adendum_log(self, body, startTime, headerTableName, rowmargin.adendum_id, 'DELETE ROW MARGIN', {adendummargin_id: rowmargin.adendummargin_id, tablename: marginTableName}, `removed: ${rowmargin.adendummargin_id}`)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}

async function adendum_marginDeleteRows(self, body) {
	const { data } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = marginTableName


	try {

		let adendum_id
		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			for (let id of data) {
				const dataToRemove = {adendummargin_id: id}
				const sql = `select * from ${marginTableName} where adendummargin_id=\${adendummargin_id}`
				const rowmargin = await tx.oneOrNone(sql, dataToRemove)
				adendum_id = rowmargin.adendum_id

				const logMetadata = {}

				
				// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
				if (typeof Extender.marginDeleting === 'function') {
					// async function marginDeleting(self, tx, rowmargin, logMetadata) {}
					await Extender.marginDeleting(self, tx, rowmargin, logMetadata)
				}

				const param = {adendummargin_id: rowmargin.adendummargin_id}
				const cmd = sqlUtil.createDeleteCommand(marginTableName, ['adendummargin_id'])
				const deletedRow = await cmd.execute(param)

				// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
				if (typeof Extender.marginDeleted === 'function') {
					// export async function marginDeleted(self, tx, deletedRow, logMetadata) {}
					await Extender.marginDeleted(self, tx, deletedRow, logMetadata)
				}					

				adendum_log(self, body, startTime, marginTableName, rowmargin.adendummargin_id, 'DELETE', {rowdata: deletedRow})
				adendum_log(self, body, startTime, headerTableName, rowmargin.adendum_id, 'DELETE ROW MARGIN', {adendummargin_id: rowmargin.adendummargin_id, tablename: marginTableName}, `removed: ${rowmargin.adendummargin_id}`)
			}
		})
		

		const res = {
			deleted: true,
			adendum_id: adendum_id,
			message: ''
		}

		// apabila ada keperluan update info / pemrosesan data setelah hapus multirow, lakukan di extender
		const fn_name = 'marginRowsDeleted'
		const fn = Extender[fn_name]
		if (typeof fn === 'function') {
			// export async function marginRowsDeleted(self, db, res) {}
			await fn(self, db, res)
		}

		return res
	} catch (err) {
		throw err
	}	
}

	