/***************************************************************** 
 * this script is generated by fgta5 generator version 1.2
 * DO NOT modify this script! All modification will lost on regeneration
 **************************************************************** */

import pgp from 'pg-promise';

import db from '@agung_dhewe/webapps/src/db.js'
import Api from '@agung_dhewe/webapps/src/api.js'
import sqlUtil from '@agung_dhewe/pgsqlc'
import context from '@agung_dhewe/webapps/src/context.js'  
import logger from '@agung_dhewe/webapps/src/logger.js'
import { createSequencerLine } from '@agung_dhewe/webapps/src/sequencerline.js' 
import bucket from '@agung_dhewe/webapps/src/bucket.js'	

import * as Extender from './extenders/agreement.apiext.js'

const moduleName = 'agreement'
const headerSectionName = 'header'
const headerTableName = 'public.agreement' 
const brandTableName = 'public.agreementbrand'  
const marginTableName = 'public.agreementmargin'  
const docTableName = 'public.agreementdoc'  	

// api: account
export default class extends Api {
	constructor(req, res, next) {
		super(req, res, next);
		Api.cekLogin(req)
	}


	// dipanggil dengan model snake syntax
	// contoh: header-list
	//         header-open-data
	async init(body) { return await agreement_init(this, body) }

	// extender call
	async execute(body) { return await agreement_execute(this, body) }

	// header
	async headerList(body) { return await agreement_headerList(this, body) }
	async headerOpen(body) { return await agreement_headerOpen(this, body) }
	async headerUpdate(body) { return await agreement_headerUpdate(this, body)}
	async headerCreate(body) { return await agreement_headerCreate(this, body)}
	async headerDelete(body) { return await agreement_headerDelete(this, body) }

	
	// brand	
	async brandList(body) { return await agreement_brandList(this, body) }
	async brandOpen(body) { return await agreement_brandOpen(this, body) }
	async brandUpdate(body) { return await agreement_brandUpdate(this, body)}
	async brandCreate(body) { return await agreement_brandCreate(this, body) }
	async brandDelete(body) { return await agreement_brandDelete(this, body) }
	async brandDeleteRows(body) { return await agreement_brandDeleteRows(this, body) }
	
	// margin	
	async marginList(body) { return await agreement_marginList(this, body) }
	async marginOpen(body) { return await agreement_marginOpen(this, body) }
	async marginUpdate(body) { return await agreement_marginUpdate(this, body)}
	async marginCreate(body) { return await agreement_marginCreate(this, body) }
	async marginDelete(body) { return await agreement_marginDelete(this, body) }
	async marginDeleteRows(body) { return await agreement_marginDeleteRows(this, body) }
	
	// doc	
	async docList(body) { return await agreement_docList(this, body) }
	async docOpen(body) { return await agreement_docOpen(this, body) }
	async docUpdate(body) { return await agreement_docUpdate(this, body)}
	async docCreate(body) { return await agreement_docCreate(this, body) }
	async docDelete(body) { return await agreement_docDelete(this, body) }
	async docDeleteRows(body) { return await agreement_docDeleteRows(this, body) }
			
}	

// init module
async function agreement_init(self, body) {
	const req = self.req

	// set sid untuk session ini, diperlukan ini agar session aktif
	req.session.sid = req.sessionID

	try {
		// ambil data app dari database
		const sql = 'select apps_id, apps_url from core."apps"'
		const result = await db.any(sql)

		const appsUrls = {}
		for (let row of result) {
			appsUrls[row.apps_id] = {
				url: row.apps_url
			}
		}

		const initialData = {
			userId: req.session.user.userId,
			userName: req.session.user.userName,
			userFullname: req.session.userFullname,
			sid: req.session.sid ,
			notifierId: Api.generateNotifierId(moduleName, req.sessionID),
			notifierSocket: req.app.locals.appConfig.notifierSocket,
			appName: req.app.locals.appConfig.appName,
			appsUrls: appsUrls,
			setting: {}
		}
		
		if (typeof Extender.agreement_init === 'function') {
			// export async function agreement_init(self, initialData) {}
			await Extender.agreement_init(self, initialData)
		}

		return initialData
		
	} catch (err) {
		throw err
	}
}


// execute extender function
async function agreement_execute(self, body) {
	const { fnName } = body

	if (fnName==null || fnName=='') {
		throw new Error('fnName belum didefinisikan di api call') 
	}

	if (typeof Extender[fnName] === 'function') {
		// export async function [fnName](self, db, body, agreement_log) {}
		return await Extender[fnName](self, db, body, agreement_log)
	} else {
		// api function extender tidak ditemukan
		throw new Error(`${fnName} tidak ditmukan di extender`)
	}
}


// data logging
async function agreement_log(self, body, startTime, tablename, id, action, data={}, remark='') {
	const { source } = body
	const req = self.req
	const user_id = req.session.user.userId
	const user_name = req.session.user.userFullname
	const ipaddress = req.ip
	const metadata = JSON.stringify({...{source:source}, ...data})
	const endTime = process.hrtime.bigint();
	const executionTimeMs = Number((endTime - startTime) / 1_000_000n); // hasil dalam ms tanpa desimal
	
	const logdata = {id, user_id, user_name, moduleName, action, tablename, executionTimeMs, remark, metadata, ipaddress}
	const ret = await logger.log(logdata)
	return ret
}




async function agreement_upload(self, data, files, detilName, id, fn_uploadSuccess) {
	const bucketname = 'agreement'
	const docid = data.agreement_id
	
	const uploads = files.map(async (file) => {
		const fieldname = file.fieldname
		const objectname = detilName=='header' ? `${docid}/${fieldname}` : `${docid}/${detilName}/${id}-${fieldname}`
		
		const metaData = {
			'Content-Type': file.mimetype,
			'X-Amz-Meta-document_id': docid,
			'X-Amz-Meta-fieldname': fieldname,
			'X-Amz-Meta-originalname': file.originalname,
		};

		if (detilName!='header') {
			metaData['X-Amz-Meta-document-rowid'] = id
		}


		// simpan di bucket
		await bucket.putObject(bucketname, objectname, file.buffer, metaData);

		// catat di log
		if (typeof fn_uploadSuccess==='function') {
			fn_uploadSuccess({
				originalname: file.originalname,
				mimetype: file.fieldname,
				size: file.size,
				bucketname,
				objectname
			})
		}
		return {fieldname, objectname};
	});

	const uploadedFiles = await Promise.all(uploads);
	return uploadedFiles
}


async function agreement_headerList(self, body) {
	const tablename = headerTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		searchtext: `agreement_id=try_cast_bigint(\${searchtext}, 0)`,
	};

	try {
	
		// jika tidak ada default searchtext
		if (searchMap.searchtext===undefined) {
			throw new Error(`'searchtext' belum didefinisikan di searchMap`)	
		}
		

		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.headerListCriteria === 'function') {
			// export async function headerListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.headerListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort,
			limit:max_rows+1, 
			offset, 
			queryParams
		})

		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			// lookup: partner_name dari field partner_name pada table public.partner dimana (public.partner.partner_id = public.agreement.partner_id)
			{
				const { partner_name } = await sqlUtil.lookupdb(db, 'public.partner', 'partner_id', row.partner_id)
				row.partner_name = partner_name
			}
			// lookup: site_name dari field site_name pada table public.site dimana (public.site.site_id = public.agreement.site_id)
			{
				const { site_name } = await sqlUtil.lookupdb(db, 'public.site', 'site_id', row.site_id)
				row.site_name = site_name
			}
			
			// pasang extender di sini
			if (typeof Extender.headerListRow === 'function') {
				// export async function headerListRow(self, row, args) {}
				await Extender.headerListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}

		return {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

	} catch (err) {
		throw err
	}
}

async function agreement_headerOpen(self, body) {
	const tablename = headerTableName

	try {
		const { id } = body 
		const criteria = { agreement_id: id }
		const searchMap = { agreement_id: `agreement_id = \${agreement_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	

		// lookup: partner_name dari field partner_name pada table public.partner dimana (public.partner.partner_id = public.agreement.partner_id)
		{
			const { partner_name } = await sqlUtil.lookupdb(db, 'public.partner', 'partner_id', data.partner_id)
			data.partner_name = partner_name
		}
		// lookup: site_name dari field site_name pada table public.site dimana (public.site.site_id = public.agreement.site_id)
		{
			const { site_name } = await sqlUtil.lookupdb(db, 'public.site', 'site_id', data.site_id)
			data.site_name = site_name
		}
		

		// lookup data createby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}
		
		// pasang extender untuk olah data
		// export async function headerOpen(self, db, data) {}
		if (typeof Extender.headerOpen === 'function') {
			// export async function headerOpen(self, db, data) {}
			await Extender.headerOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}


async function agreement_headerCreate(self, body) {
	const { source='agreement', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = headerTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._createby = user_id
		data._createdate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { section: 'header', doc_id:'AGR' }

			
			// buat short sequencer	
			const sequencer = createSequencerLine(tx, {})

			if (typeof Extender.sequencerSetup === 'function') {
				// jika ada keperluan menambahkan code block/cluster di sequencer
				// dapat diimplementasikan di exterder sequencerSetup 
				// export async function sequencerSetup(self, tx, sequencer, data, args) {}
				await Extender.sequencerSetup(self, tx, sequencer, data, args)
			}

			// generate short id sesuai prefix (default: AGR) reset pertahun
			const seqdata = await sequencer.yearlyshort(args.doc_id)
			data.agreement_id = seqdata.id

			// apabila ada keperluan pengelohan data sebelum disimpan, lakukan di extender headerCreating
			if (typeof Extender.headerCreating === 'function') {
				// export async function headerCreating(self, tx, data, seqdata, args) {}
				await Extender.headerCreating(self, tx, data, seqdata, args)
			}

			

			const cmd = sqlUtil.createInsertCommand(tablename, data)
			const ret = await cmd.execute(data)

			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.headerCreated === 'function') {
				// export async function headerCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.headerCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			agreement_log(self, body, startTime, tablename, ret.agreement_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function agreement_headerUpdate(self, body) {
	const { source='agreement', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = headerTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._modifyby = user_id
		data._modifydate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			// apabila ada keperluan pengelohan data sebelum disimpan, lakukan di extender headerCreating
			if (typeof Extender.headerUpdating === 'function') {
				// export async function headerUpdating(self, tx, data) {}
				await Extender.headerUpdating(self, tx, data)
			}

			// eksekusi update
			const cmd = sqlUtil.createUpdateCommand(tablename, data, ['agreement_id'])
			const ret = await cmd.execute(data)

			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.headerUpdated === 'function') {
				// export async function headerUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.headerUpdated(self, tx, ret, data, logMetadata)
			}			

			// record log
			agreement_log(self, body, startTime, tablename, data.agreement_id, 'UPDATE')

			return ret
		})
		

		return result
	} catch (err) {
		throw err
	}
}


async function agreement_headerDelete(self, body) {
	const { source, id } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = headerTableName

	try {

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {agreement_id: id}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender headerDeleting
			if (typeof Extender.headerDeleting === 'function') {
				// export async function headerDeleting(self, tx, dataToRemove) {}
				await Extender.headerDeleting(self, tx, dataToRemove)
			}

			
			// hapus data brand
			{
				const sql = `select * from ${brandTableName} where agreement_id=\${agreement_id}`
				const rows = await tx.any(sql, dataToRemove)
				for (let rowbrand of rows) {
					
					const logMetadata = {}
					
					// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
					if (typeof Extender.brandDeleting === 'function') {
						// export async function brandDeleting(self, tx, rowbrand, logMetadata) {}
						await Extender.brandDeleting(self, tx, rowbrand, logMetadata)
					}

					const param = {agreementbrand_id: rowbrand.agreementbrand_id}
					const cmd = sqlUtil.createDeleteCommand(brandTableName, ['agreementbrand_id'])
					const deletedRow = await cmd.execute(param)

					// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
					if (typeof Extender.brandDeleted === 'function') {
						// export async function brandDeleted(self, tx, deletedRow, logMetadata) {}
						await Extender.brandDeleted(self, tx, deletedRow, logMetadata)
					}					

					agreement_log(self, body, startTime, brandTableName, rowbrand.agreementbrand_id, 'DELETE', {rowdata: deletedRow})
					agreement_log(self, body, startTime, headerTableName, rowbrand.agreement_id, 'DELETE ROW BRAND', {agreementbrand_id: rowbrand.agreementbrand_id, tablename: brandTableName}, `removed: ${rowbrand.agreementbrand_id}`)


				}	
			}

			// hapus data margin
			{
				const sql = `select * from ${marginTableName} where agreement_id=\${agreement_id}`
				const rows = await tx.any(sql, dataToRemove)
				for (let rowmargin of rows) {
					
					const logMetadata = {}
					
					// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
					if (typeof Extender.marginDeleting === 'function') {
						// export async function marginDeleting(self, tx, rowmargin, logMetadata) {}
						await Extender.marginDeleting(self, tx, rowmargin, logMetadata)
					}

					const param = {agreementmargin_id: rowmargin.agreementmargin_id}
					const cmd = sqlUtil.createDeleteCommand(marginTableName, ['agreementmargin_id'])
					const deletedRow = await cmd.execute(param)

					// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
					if (typeof Extender.marginDeleted === 'function') {
						// export async function marginDeleted(self, tx, deletedRow, logMetadata) {}
						await Extender.marginDeleted(self, tx, deletedRow, logMetadata)
					}					

					agreement_log(self, body, startTime, marginTableName, rowmargin.agreementmargin_id, 'DELETE', {rowdata: deletedRow})
					agreement_log(self, body, startTime, headerTableName, rowmargin.agreement_id, 'DELETE ROW MARGIN', {agreementmargin_id: rowmargin.agreementmargin_id, tablename: marginTableName}, `removed: ${rowmargin.agreementmargin_id}`)


				}	
			}

			// hapus data doc
			{
				const sql = `select * from ${docTableName} where agreement_id=\${agreement_id}`
				const rows = await tx.any(sql, dataToRemove)
				for (let rowdoc of rows) {
					
					const logMetadata = {}
					
					// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
					if (typeof Extender.docDeleting === 'function') {
						// export async function docDeleting(self, tx, rowdoc, logMetadata) {}
						await Extender.docDeleting(self, tx, rowdoc, logMetadata)
					}

					const param = {agreementdoc_id: rowdoc.agreementdoc_id}
					const cmd = sqlUtil.createDeleteCommand(docTableName, ['agreementdoc_id'])
					const deletedRow = await cmd.execute(param)

					// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
					if (typeof Extender.docDeleted === 'function') {
						// export async function docDeleted(self, tx, deletedRow, logMetadata) {}
						await Extender.docDeleted(self, tx, deletedRow, logMetadata)
					}					

					agreement_log(self, body, startTime, docTableName, rowdoc.agreementdoc_id, 'DELETE', {rowdata: deletedRow})
					agreement_log(self, body, startTime, headerTableName, rowdoc.agreement_id, 'DELETE ROW DOC', {agreementdoc_id: rowdoc.agreementdoc_id, tablename: docTableName}, `removed: ${rowdoc.agreementdoc_id}`)


				}	
			}

			
			

			// hapus data header
			const cmd = sqlUtil.createDeleteCommand(tablename, ['agreement_id'])
			const deletedRow = await cmd.execute(dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender headerDeleted
			if (typeof Extender.headerDeleted === 'function') {
				// export async function headerDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.headerDeleted(self, tx, deletedRow, logMetadata)
			}

			// record log
			agreement_log(self, body, startTime, tablename, id, 'DELETE', logMetadata)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}



// brand	

async function agreement_brandList(self, body) {
	const tablename = brandTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		agreement_id: `agreement_id=try_cast_bigint(\${agreement_id}, 0)`,
	};


	if (Object.keys(sort).length === 0) {
		sort.agreementbrand_id = 'asc'
	}


	try {
	
		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.brandListCriteria === 'function') {
			// export async function brandListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.brandListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort, 
			limit:max_rows+1, 
			offset, 
			queryParams
		})
		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			// lookup: brand_name dari field brand_name pada table public.brand dimana (public.brand.brand_id = public.agreement.brand_id)
			{
				const { brand_name } = await sqlUtil.lookupdb(db, 'public.brand', 'brand_id', row.brand_id)
				row.brand_name = brand_name
			}
			

			// pasang extender di sini
			if (typeof Extender.detilListRow === 'function') {
				// export async function detilListRow(self, row, args) {}
				await Extender.detilListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}


		const listData = {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

		if (typeof Extender.detilList === 'function') {
			// export async function detilList(self, listData, args) {}
			await Extender.detilList(self, listData, args)
		}

		return listData
	} catch (err) {
		throw err
	}
}

async function agreement_brandOpen(self, body) {
	const tablename = brandTableName

	try {
		const { id } = body 
		const criteria = { agreementbrand_id: id }
		const searchMap = { agreementbrand_id: `agreementbrand_id = \${agreementbrand_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	


		// lookup: brand_name dari field brand_name pada table public.brand dimana (public.brand.brand_id = public.agreement.brand_id)
		{
			const { brand_name } = await sqlUtil.lookupdb(db, 'public.brand', 'brand_id', data.brand_id)
			data.brand_name = brand_name
		}
		

		// lookup data createby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}	


		// pasang extender untuk olah data
		// export async function brandOpen(self, db, data) {}
		if (typeof Extender.brandOpen === 'function') {
			// export async function brandOpen(self, db, data) {}
			await Extender.brandOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}

async function agreement_brandCreate(self, body) {
	const { source='agreement', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = brandTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._createby = user_id
		data._createdate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { 
				section: 'brand', 
				prefix: 'AGR'	
			}

			const sequencer = createSequencerLine(tx, {})


			if (typeof Extender.sequencerSetup === 'function') {
				// jika ada keperluan menambahkan code block/cluster di sequencer
				// dapat diimplementasikan di exterder sequencerSetup 
				// export async function sequencerSetup(self, tx, sequencer, data, args) {}
				await Extender.sequencerSetup(self, tx, sequencer, data, args)
			}


			const seqdata = await sequencer.increment(args.prefix)
			data.agreementbrand_id = seqdata.id

			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.brandCreating === 'function') {
				// export async function brandCreating(self, tx, data, seqdata, args) {}
				await Extender.brandCreating(self, tx, data, seqdata, args)
			}

			const cmd = sqlUtil.createInsertCommand(tablename, data)
			const ret = await cmd.execute(data)
			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.brandCreated === 'function') {
				// export async function brandCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.brandCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			agreement_log(self, body, startTime, tablename, ret.agreementbrand_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function agreement_brandUpdate(self, body) {
	const { source='agreement', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = brandTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._modifyby = user_id
		data._modifydate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.brandUpdating === 'function') {
				// export async function brandUpdating(self, tx, data) {}
				await Extender.brandUpdating(self, tx, data)
			}			
			
			const cmd =  sqlUtil.createUpdateCommand(tablename, data, ['agreementbrand_id'])
			const ret = await cmd.execute(data)
			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.brandUpdated === 'function') {
				// export async function brandUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.brandUpdated(self, tx, ret, data, logMetadata)
			}

			// record log
			agreement_log(self, body, startTime, tablename, data.agreementbrand_id, 'UPDATE', logMetadata)

			return ret
		})
	
		return result
	} catch (err) {
		throw err
	}
}

async function agreement_brandDelete(self, body) {
	const { source, id } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = brandTableName

	try {

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {agreementbrand_id: id}
			const sql = `select * from ${brandTableName} where agreementbrand_id=\${agreementbrand_id}`
			const rowbrand = await tx.oneOrNone(sql, dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
			if (typeof Extender.brandDeleting === 'function') {
				// export async function brandDeleting(self, tx, rowbrand, logMetadata) {}
				await Extender.brandDeleting(self, tx, rowbrand, logMetadata)
			}

			const param = {agreementbrand_id: rowbrand.agreementbrand_id}
			const cmd = sqlUtil.createDeleteCommand(brandTableName, ['agreementbrand_id'])
			const deletedRow = await cmd.execute(param)

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
			if (typeof Extender.brandDeleted === 'function') {
				// export async function brandDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.brandDeleted(self, tx, deletedRow, logMetadata)
			}					

			agreement_log(self, body, startTime, brandTableName, rowbrand.agreementbrand_id, 'DELETE', {rowdata: deletedRow})
			agreement_log(self, body, startTime, headerTableName, rowbrand.agreement_id, 'DELETE ROW BRAND', {agreementbrand_id: rowbrand.agreementbrand_id, tablename: brandTableName}, `removed: ${rowbrand.agreementbrand_id}`)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}

async function agreement_brandDeleteRows(self, body) {
	const { data } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = brandTableName


	try {

		let agreement_id
		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			for (let id of data) {
				const dataToRemove = {agreementbrand_id: id}
				const sql = `select * from ${brandTableName} where agreementbrand_id=\${agreementbrand_id}`
				const rowbrand = await tx.oneOrNone(sql, dataToRemove)
				agreement_id = rowbrand.agreement_id

				const logMetadata = {}

				
				// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
				if (typeof Extender.brandDeleting === 'function') {
					// async function brandDeleting(self, tx, rowbrand, logMetadata) {}
					await Extender.brandDeleting(self, tx, rowbrand, logMetadata)
				}

				const param = {agreementbrand_id: rowbrand.agreementbrand_id}
				const cmd = sqlUtil.createDeleteCommand(brandTableName, ['agreementbrand_id'])
				const deletedRow = await cmd.execute(param)

				// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
				if (typeof Extender.brandDeleted === 'function') {
					// export async function brandDeleted(self, tx, deletedRow, logMetadata) {}
					await Extender.brandDeleted(self, tx, deletedRow, logMetadata)
				}					

				agreement_log(self, body, startTime, brandTableName, rowbrand.agreementbrand_id, 'DELETE', {rowdata: deletedRow})
				agreement_log(self, body, startTime, headerTableName, rowbrand.agreement_id, 'DELETE ROW BRAND', {agreementbrand_id: rowbrand.agreementbrand_id, tablename: brandTableName}, `removed: ${rowbrand.agreementbrand_id}`)
			}
		})
		

		const res = {
			deleted: true,
			agreement_id: agreement_id,
			message: ''
		}

		// apabila ada keperluan update info / pemrosesan data setelah hapus multirow, lakukan di extender
		const fn_name = 'brandRowsDeleted'
		const fn = Extender[fn_name]
		if (typeof fn === 'function') {
			// export async function brandRowsDeleted(self, db, res) {}
			await fn(self, db, res)
		}

		return res
	} catch (err) {
		throw err
	}	
}


// margin	

async function agreement_marginList(self, body) {
	const tablename = marginTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		agreement_id: `agreement_id=try_cast_bigint(\${agreement_id}, 0)`,
	};


	if (Object.keys(sort).length === 0) {
		sort.agreementmargin_id = 'asc'
	}


	try {
	
		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.marginListCriteria === 'function') {
			// export async function marginListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.marginListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort, 
			limit:max_rows+1, 
			offset, 
			queryParams
		})
		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			// lookup: marginrange_desc dari field marginrange_desc pada table public.marginrange dimana (public.marginrange.marginrange_id = public.agreement.marginrange_id)
			{
				const { marginrange_desc } = await sqlUtil.lookupdb(db, 'public.marginrange', 'marginrange_id', row.marginrange_id)
				row.marginrange_desc = marginrange_desc
			}
			

			// pasang extender di sini
			if (typeof Extender.detilListRow === 'function') {
				// export async function detilListRow(self, row, args) {}
				await Extender.detilListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}


		const listData = {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

		if (typeof Extender.detilList === 'function') {
			// export async function detilList(self, listData, args) {}
			await Extender.detilList(self, listData, args)
		}

		return listData
	} catch (err) {
		throw err
	}
}

async function agreement_marginOpen(self, body) {
	const tablename = marginTableName

	try {
		const { id } = body 
		const criteria = { agreementmargin_id: id }
		const searchMap = { agreementmargin_id: `agreementmargin_id = \${agreementmargin_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	


		// lookup: marginrange_desc dari field marginrange_desc pada table public.marginrange dimana (public.marginrange.marginrange_id = public.agreement.marginrange_id)
		{
			const { marginrange_desc } = await sqlUtil.lookupdb(db, 'public.marginrange', 'marginrange_id', data.marginrange_id)
			data.marginrange_desc = marginrange_desc
		}
		

		// lookup data createby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}	


		// pasang extender untuk olah data
		// export async function marginOpen(self, db, data) {}
		if (typeof Extender.marginOpen === 'function') {
			// export async function marginOpen(self, db, data) {}
			await Extender.marginOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}

async function agreement_marginCreate(self, body) {
	const { source='agreement', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = marginTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._createby = user_id
		data._createdate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { 
				section: 'margin', 
				prefix: 'AGR'	
			}

			const sequencer = createSequencerLine(tx, {})


			if (typeof Extender.sequencerSetup === 'function') {
				// jika ada keperluan menambahkan code block/cluster di sequencer
				// dapat diimplementasikan di exterder sequencerSetup 
				// export async function sequencerSetup(self, tx, sequencer, data, args) {}
				await Extender.sequencerSetup(self, tx, sequencer, data, args)
			}


			const seqdata = await sequencer.increment(args.prefix)
			data.agreementmargin_id = seqdata.id

			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.marginCreating === 'function') {
				// export async function marginCreating(self, tx, data, seqdata, args) {}
				await Extender.marginCreating(self, tx, data, seqdata, args)
			}

			const cmd = sqlUtil.createInsertCommand(tablename, data)
			const ret = await cmd.execute(data)
			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.marginCreated === 'function') {
				// export async function marginCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.marginCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			agreement_log(self, body, startTime, tablename, ret.agreementmargin_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function agreement_marginUpdate(self, body) {
	const { source='agreement', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = marginTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._modifyby = user_id
		data._modifydate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.marginUpdating === 'function') {
				// export async function marginUpdating(self, tx, data) {}
				await Extender.marginUpdating(self, tx, data)
			}			
			
			const cmd =  sqlUtil.createUpdateCommand(tablename, data, ['agreementmargin_id'])
			const ret = await cmd.execute(data)
			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.marginUpdated === 'function') {
				// export async function marginUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.marginUpdated(self, tx, ret, data, logMetadata)
			}

			// record log
			agreement_log(self, body, startTime, tablename, data.agreementmargin_id, 'UPDATE', logMetadata)

			return ret
		})
	
		return result
	} catch (err) {
		throw err
	}
}

async function agreement_marginDelete(self, body) {
	const { source, id } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = marginTableName

	try {

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {agreementmargin_id: id}
			const sql = `select * from ${marginTableName} where agreementmargin_id=\${agreementmargin_id}`
			const rowmargin = await tx.oneOrNone(sql, dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
			if (typeof Extender.marginDeleting === 'function') {
				// export async function marginDeleting(self, tx, rowmargin, logMetadata) {}
				await Extender.marginDeleting(self, tx, rowmargin, logMetadata)
			}

			const param = {agreementmargin_id: rowmargin.agreementmargin_id}
			const cmd = sqlUtil.createDeleteCommand(marginTableName, ['agreementmargin_id'])
			const deletedRow = await cmd.execute(param)

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
			if (typeof Extender.marginDeleted === 'function') {
				// export async function marginDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.marginDeleted(self, tx, deletedRow, logMetadata)
			}					

			agreement_log(self, body, startTime, marginTableName, rowmargin.agreementmargin_id, 'DELETE', {rowdata: deletedRow})
			agreement_log(self, body, startTime, headerTableName, rowmargin.agreement_id, 'DELETE ROW MARGIN', {agreementmargin_id: rowmargin.agreementmargin_id, tablename: marginTableName}, `removed: ${rowmargin.agreementmargin_id}`)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}

async function agreement_marginDeleteRows(self, body) {
	const { data } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = marginTableName


	try {

		let agreement_id
		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			for (let id of data) {
				const dataToRemove = {agreementmargin_id: id}
				const sql = `select * from ${marginTableName} where agreementmargin_id=\${agreementmargin_id}`
				const rowmargin = await tx.oneOrNone(sql, dataToRemove)
				agreement_id = rowmargin.agreement_id

				const logMetadata = {}

				
				// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
				if (typeof Extender.marginDeleting === 'function') {
					// async function marginDeleting(self, tx, rowmargin, logMetadata) {}
					await Extender.marginDeleting(self, tx, rowmargin, logMetadata)
				}

				const param = {agreementmargin_id: rowmargin.agreementmargin_id}
				const cmd = sqlUtil.createDeleteCommand(marginTableName, ['agreementmargin_id'])
				const deletedRow = await cmd.execute(param)

				// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
				if (typeof Extender.marginDeleted === 'function') {
					// export async function marginDeleted(self, tx, deletedRow, logMetadata) {}
					await Extender.marginDeleted(self, tx, deletedRow, logMetadata)
				}					

				agreement_log(self, body, startTime, marginTableName, rowmargin.agreementmargin_id, 'DELETE', {rowdata: deletedRow})
				agreement_log(self, body, startTime, headerTableName, rowmargin.agreement_id, 'DELETE ROW MARGIN', {agreementmargin_id: rowmargin.agreementmargin_id, tablename: marginTableName}, `removed: ${rowmargin.agreementmargin_id}`)
			}
		})
		

		const res = {
			deleted: true,
			agreement_id: agreement_id,
			message: ''
		}

		// apabila ada keperluan update info / pemrosesan data setelah hapus multirow, lakukan di extender
		const fn_name = 'marginRowsDeleted'
		const fn = Extender[fn_name]
		if (typeof fn === 'function') {
			// export async function marginRowsDeleted(self, db, res) {}
			await fn(self, db, res)
		}

		return res
	} catch (err) {
		throw err
	}	
}


// doc	

async function agreement_docList(self, body) {
	const tablename = docTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		agreement_id: `agreement_id=try_cast_bigint(\${agreement_id}, 0)`,
	};


	if (Object.keys(sort).length === 0) {
		sort.agreementdoc_id = 'asc'
	}


	try {
	
		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.docListCriteria === 'function') {
			// export async function docListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.docListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort, 
			limit:max_rows+1, 
			offset, 
			queryParams
		})
		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			

			// pasang extender di sini
			if (typeof Extender.detilListRow === 'function') {
				// export async function detilListRow(self, row, args) {}
				await Extender.detilListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}


		const listData = {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

		if (typeof Extender.detilList === 'function') {
			// export async function detilList(self, listData, args) {}
			await Extender.detilList(self, listData, args)
		}

		return listData
	} catch (err) {
		throw err
	}
}

async function agreement_docOpen(self, body) {
	const tablename = docTableName

	try {
		const { id } = body 
		const criteria = { agreementdoc_id: id }
		const searchMap = { agreementdoc_id: `agreementdoc_id = \${agreementdoc_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	


		

		// lookup data createby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}	


		// pasang extender untuk olah data
		// export async function docOpen(self, db, data) {}
		if (typeof Extender.docOpen === 'function') {
			// export async function docOpen(self, db, data) {}
			await Extender.docOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}

async function agreement_docCreate(self, body) {
	const { source='agreement', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = docTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._createby = user_id
		data._createdate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { 
				section: 'doc', 
				prefix: 'AGR'	
			}

			const sequencer = createSequencerLine(tx, {})


			if (typeof Extender.sequencerSetup === 'function') {
				// jika ada keperluan menambahkan code block/cluster di sequencer
				// dapat diimplementasikan di exterder sequencerSetup 
				// export async function sequencerSetup(self, tx, sequencer, data, args) {}
				await Extender.sequencerSetup(self, tx, sequencer, data, args)
			}


			const seqdata = await sequencer.increment(args.prefix)
			data.agreementdoc_id = seqdata.id

			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.docCreating === 'function') {
				// export async function docCreating(self, tx, data, seqdata, args) {}
				await Extender.docCreating(self, tx, data, seqdata, args)
			}

			const cmd = sqlUtil.createInsertCommand(tablename, data)
			const ret = await cmd.execute(data)
			
			// jika ada file yang diupload di doc
			if (files!=null) {
				agreement_upload(self, ret, files, 'doc', ret.agreementdoc_id,  (result)=>{
					agreement_log(self, body, startTime, tablename, ret.agreementdoc_id, 'UPLOAD FILE', result, `${result.originalname}`)
				})
			}
			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.docCreated === 'function') {
				// export async function docCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.docCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			agreement_log(self, body, startTime, tablename, ret.agreementdoc_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function agreement_docUpdate(self, body) {
	const { source='agreement', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = docTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._modifyby = user_id
		data._modifydate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.docUpdating === 'function') {
				// export async function docUpdating(self, tx, data) {}
				await Extender.docUpdating(self, tx, data)
			}			
			
			const cmd =  sqlUtil.createUpdateCommand(tablename, data, ['agreementdoc_id'])
			const ret = await cmd.execute(data)
			
			// jika ada file yang diupload di doc
			if (files!=null) {
				agreement_upload(self, ret, files, 'doc', ret.agreementdoc_id,  (result)=>{
					agreement_log(self, body, startTime, tablename, ret.agreementdoc_id, 'UPLOAD FILE', result, `${result.originalname}`)
				})
			}
			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.docUpdated === 'function') {
				// export async function docUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.docUpdated(self, tx, ret, data, logMetadata)
			}

			// record log
			agreement_log(self, body, startTime, tablename, data.agreementdoc_id, 'UPDATE', logMetadata)

			return ret
		})
	
		return result
	} catch (err) {
		throw err
	}
}

async function agreement_docDelete(self, body) {
	const { source, id } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = docTableName

	try {

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {agreementdoc_id: id}
			const sql = `select * from ${docTableName} where agreementdoc_id=\${agreementdoc_id}`
			const rowdoc = await tx.oneOrNone(sql, dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
			if (typeof Extender.docDeleting === 'function') {
				// export async function docDeleting(self, tx, rowdoc, logMetadata) {}
				await Extender.docDeleting(self, tx, rowdoc, logMetadata)
			}

			const param = {agreementdoc_id: rowdoc.agreementdoc_id}
			const cmd = sqlUtil.createDeleteCommand(docTableName, ['agreementdoc_id'])
			const deletedRow = await cmd.execute(param)

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
			if (typeof Extender.docDeleted === 'function') {
				// export async function docDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.docDeleted(self, tx, deletedRow, logMetadata)
			}					

			agreement_log(self, body, startTime, docTableName, rowdoc.agreementdoc_id, 'DELETE', {rowdata: deletedRow})
			agreement_log(self, body, startTime, headerTableName, rowdoc.agreement_id, 'DELETE ROW DOC', {agreementdoc_id: rowdoc.agreementdoc_id, tablename: docTableName}, `removed: ${rowdoc.agreementdoc_id}`)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}

async function agreement_docDeleteRows(self, body) {
	const { data } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = docTableName


	try {

		let agreement_id
		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			for (let id of data) {
				const dataToRemove = {agreementdoc_id: id}
				const sql = `select * from ${docTableName} where agreementdoc_id=\${agreementdoc_id}`
				const rowdoc = await tx.oneOrNone(sql, dataToRemove)
				agreement_id = rowdoc.agreement_id

				const logMetadata = {}

				
				// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
				if (typeof Extender.docDeleting === 'function') {
					// async function docDeleting(self, tx, rowdoc, logMetadata) {}
					await Extender.docDeleting(self, tx, rowdoc, logMetadata)
				}

				const param = {agreementdoc_id: rowdoc.agreementdoc_id}
				const cmd = sqlUtil.createDeleteCommand(docTableName, ['agreementdoc_id'])
				const deletedRow = await cmd.execute(param)

				// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
				if (typeof Extender.docDeleted === 'function') {
					// export async function docDeleted(self, tx, deletedRow, logMetadata) {}
					await Extender.docDeleted(self, tx, deletedRow, logMetadata)
				}					

				agreement_log(self, body, startTime, docTableName, rowdoc.agreementdoc_id, 'DELETE', {rowdata: deletedRow})
				agreement_log(self, body, startTime, headerTableName, rowdoc.agreement_id, 'DELETE ROW DOC', {agreementdoc_id: rowdoc.agreementdoc_id, tablename: docTableName}, `removed: ${rowdoc.agreementdoc_id}`)
			}
		})
		

		const res = {
			deleted: true,
			agreement_id: agreement_id,
			message: ''
		}

		// apabila ada keperluan update info / pemrosesan data setelah hapus multirow, lakukan di extender
		const fn_name = 'docRowsDeleted'
		const fn = Extender[fn_name]
		if (typeof fn === 'function') {
			// export async function docRowsDeleted(self, db, res) {}
			await fn(self, db, res)
		}

		return res
	} catch (err) {
		throw err
	}	
}

	